# frozen_string_literal: true

require "minitest/autorun"
require "tmpdir"
require "liquid/spec/cli/adapter_dsl"
require_relative "../spec/support/liquid_vm_artifact_protocol"

class LiquidVmOptionalTest < Minitest::Test
  def test_optional_adapter_shim_skips_cleanly_when_private_checkout_is_absent
    assert_optional_adapter_skips("../spec/liquid_vm.rb", "LIQUID_VM_ADAPTER", "Shopify/liquid-vm is optional")
  end

  def test_optional_ssa_adapter_shim_skips_cleanly_when_private_checkout_is_absent
    assert_optional_adapter_skips("../spec/liquid_vm_ssa.rb", "LIQUID_VM_SSA_ADAPTER", "Shopify/liquid-vm SSA is optional")
  end

  def test_default_matrix_does_not_include_private_liquid_vm_adapter
    rakefile = File.read(File.expand_path("../Rakefile", __dir__), encoding: Encoding::UTF_8)

    assert_includes rakefile, 'ENV["WITH_LIQUID_VM"] == "1"'
    assert_includes rakefile, "ADAPTER_VM_SSA"
    refute_match(/File\.exist\?\(ADAPTER_VM\)/, rakefile)
  end

  # The private adapter gives Liquid::Registers its input Hash directly. The
  # protocol wrapper must stop cycle/runtime state from leaking to the next
  # correctness render without deep-copying the large assigns tree.
  def test_artifact_protocol_isolates_register_hash_per_render
    LiquidSpec.reset!
    observed = []
    LiquidSpec.compile { |_ctx, _source, _options| }
    LiquidSpec.render do |_ctx, _assigns, options|
      observed << options.fetch(:registers).object_id
      options.fetch(:registers)[:cycle_state] = 1
      "ok"
    end

    LiquidVmArtifactProtocol.install!(backend: :vm)
    registers = { file_system: :fs }
    options = { registers: registers }

    assert_equal "ok", LiquidSpec.render_block.call({}, {}, options)
    assert_equal "ok", LiquidSpec.render_block.call({}, {}, options)
    refute_equal observed[0], observed[1]
    assert_equal({ file_system: :fs }, registers)
  ensure
    LiquidSpec.reset!
  end

  # Artifact serialization must not inflate source compile+render timing. The
  # benchmark harness invokes the dump hook separately and outside that lane.
  def test_artifact_protocol_only_serializes_in_dump_hook
    LiquidSpec.reset!
    serialize_calls = 0
    template = Object.new
    template.define_singleton_method(:serialize) do
      serialize_calls += 1
      "root-bytecode"
    end
    LiquidSpec.compile { |ctx, _source, _options| ctx[:template] = template }
    LiquidSpec.render { |_ctx, _assigns, _options| "ok" }
    LiquidVmArtifactProtocol.install!(backend: :vm)

    ctx = {}
    LiquidSpec.compile_block.call(ctx, "source", { error_mode: :strict })
    assert_equal 0, serialize_calls

    blob = LiquidSpec.dump_artifact_block.call(ctx)
    assert_kind_of String, blob
    assert_equal 1, serialize_calls
  ensure
    LiquidSpec.reset!
  end

  # Persist the exact partial bytecode generated by the adapter's shared
  # compiler. Independently recompiling it can change VM cycle/scope identity.
  def test_artifact_protocol_serializes_adapter_compiled_partials
    template = Struct.new(:name) do
      def serialize = "adapter-bytecode"
    end.new("card")
    cached = Struct.new(:compiled_template, :custom_renderer).new(template, nil)
    fetches = []
    store = Object.new
    store.define_singleton_method(:fetch) do |*args|
      fetches << args
      cached
    end
    file_system = Struct.new(:data).new({ "card" => "source is deliberately unused" })

    result = LiquidVmArtifactProtocol.serialize_partials(
      { cached_partials: store },
      { file_system: file_system, error_mode: :strict },
    )

    assert_equal [["card", 0, "strict"]], fetches
    assert_equal "adapter-bytecode", result.dig("card", "template")
    assert_equal "card", result.dig("card", "name")
  end

  private

  def assert_optional_adapter_skips(adapter_path, adapter_env_key, message)
    Dir.mktmpdir("missing-liquid-vm") do |dir|
      with_env("LIQUID_VM_PATH" => File.join(dir, "liquid-vm"), adapter_env_key => nil) do
        LiquidSpec.reset!
        load File.expand_path(adapter_path, __dir__)

        assert LiquidSpec.compile_block, "shim should define a compile block even when skipped"
        assert LiquidSpec.render_block, "shim should define a render block even when skipped"

        error = assert_raises(LiquidSpec::SkipAdapter) { LiquidSpec.run_setup! }
        assert_includes error.message, message
      ensure
        LiquidSpec.reset!
      end
    end
  end


  def with_env(values)
    old = values.transform_values { nil }
    values.each_key { |key| old[key] = ENV[key] }
    values.each do |key, value|
      value.nil? ? ENV.delete(key) : ENV[key] = value
    end
    yield
  ensure
    old.each do |key, value|
      value.nil? ? ENV.delete(key) : ENV[key] = value
    end
  end
end
